bl_info = {
    "name": "Export Scene as BPY Code",
    "author": "BVB Tools",
    "version": (1, 1, 0),
    "blender": (3, 6, 0),
    "location": "File > Export > Blender Python Script (.py)",
    "description": "Export the current scene as a reproducible bpy Python script",
    "category": "Import-Export",
}

import bpy
import math
from bpy_extras.io_utils import ExportHelper
from bpy.props import StringProperty, BoolProperty, EnumProperty


class ExportBpyCode(bpy.types.Operator, ExportHelper):
    """Export the current scene as a bpy Python script that can reconstruct it"""
    bl_idname = "export_scene.bpy_code"
    bl_label = "Export BPY Code"

    filename_ext = ".py"

    filter_glob: StringProperty(
        default="*.py",
        options={'HIDDEN'},
        maxlen=255,
    )

    include_clear_scene: BoolProperty(
        name="Include Clear Scene",
        description="Add code to clear the scene before rebuilding",
        default=True,
    )

    include_camera: BoolProperty(
        name="Include Camera",
        description="Export camera objects",
        default=True,
    )

    include_lights: BoolProperty(
        name="Include Lights",
        description="Export light objects",
        default=True,
    )

    include_render_settings: BoolProperty(
        name="Include Render Settings",
        description="Export render engine and resolution settings",
        default=False,
    )

    decimal_places: EnumProperty(
        name="Precision",
        description="Number of decimal places for coordinates",
        items=[
            ('4', "4 digits", ""),
            ('6', "6 digits (default)", ""),
            ('8', "8 digits", ""),
        ],
        default='6',
    )

    def execute(self, context):
        return self.export_scene(context, self.filepath)

    def export_scene(self, context, filepath):
        dp = int(self.decimal_places)
        lines = []

        lines.append('"""')
        lines.append(f"Blender Scene: {bpy.path.basename(bpy.data.filepath) or 'Untitled'}")
        lines.append(f"Objects: {len(bpy.data.objects)}")
        lines.append(f"Materials: {len(bpy.data.materials)}")
        lines.append(f"Generated by Export BPY Code addon v{'.'.join(str(x) for x in bl_info['version'])}")
        lines.append('"""')
        lines.append("")
        lines.append("import bpy")
        lines.append("import math")
        lines.append("")

        # --- Clear Scene ---
        if self.include_clear_scene:
            lines.append("# ============================================================")
            lines.append("# Clear Scene")
            lines.append("# ============================================================")
            lines.append("bpy.ops.object.select_all(action='SELECT')")
            lines.append("bpy.ops.object.delete(use_global=False)")
            lines.append("for m in list(bpy.data.materials): bpy.data.materials.remove(m)")
            lines.append("for m in list(bpy.data.meshes): bpy.data.meshes.remove(m)")
            lines.append("for m in list(bpy.data.lights): bpy.data.lights.remove(m)")
            lines.append("for m in list(bpy.data.cameras): bpy.data.cameras.remove(m)")
            lines.append("")

        # --- Render Settings ---
        if self.include_render_settings:
            scene = context.scene
            lines.append("# ============================================================")
            lines.append("# Render Settings")
            lines.append("# ============================================================")
            lines.append(f"bpy.context.scene.render.engine = '{scene.render.engine}'")
            lines.append(f"bpy.context.scene.render.resolution_x = {scene.render.resolution_x}")
            lines.append(f"bpy.context.scene.render.resolution_y = {scene.render.resolution_y}")
            lines.append(f"bpy.context.scene.render.resolution_percentage = {scene.render.resolution_percentage}")
            if scene.render.engine == 'CYCLES':
                lines.append(f"bpy.context.scene.cycles.samples = {scene.cycles.samples}")
            lines.append("")

        # --- Materials ---
        lines.append("# ============================================================")
        lines.append("# Materials")
        lines.append("# ============================================================")
        for mat in bpy.data.materials:
            if not mat.use_nodes or not mat.node_tree:
                continue
            bsdf = None
            for node in mat.node_tree.nodes:
                if node.type == 'BSDF_PRINCIPLED':
                    bsdf = node
                    break
            if not bsdf:
                continue

            var = self._mat_var(mat.name)
            bc = self._round_tuple(bsdf.inputs['Base Color'].default_value, dp)
            rough = round(bsdf.inputs['Roughness'].default_value, dp)
            metal = round(bsdf.inputs['Metallic'].default_value, dp)

            lines.append(f"{var} = bpy.data.materials.new(name='{mat.name}')")
            lines.append(f"{var}.use_nodes = True")
            lines.append(f"_bsdf = {var}.node_tree.nodes['Principled BSDF']")
            lines.append(f"_bsdf.inputs['Base Color'].default_value = {bc}")
            lines.append(f"_bsdf.inputs['Roughness'].default_value = {rough}")
            lines.append(f"_bsdf.inputs['Metallic'].default_value = {metal}")

            # Alpha (only if non-opaque)
            if 'Alpha' in bsdf.inputs:
                alpha = round(bsdf.inputs['Alpha'].default_value, dp)
                if alpha < 0.999:
                    lines.append(f"_bsdf.inputs['Alpha'].default_value = {alpha}")
                    lines.append(f"{var}.blend_method = 'BLEND'")

            # Emission (only export if strength > 0)
            if 'Emission Strength' in bsdf.inputs:
                es = bsdf.inputs['Emission Strength'].default_value
                if es > 0.001:
                    lines.append(f"_bsdf.inputs['Emission Strength'].default_value = {round(es, dp)}")
                    if 'Emission Color' in bsdf.inputs:
                        ec = self._round_tuple(bsdf.inputs['Emission Color'].default_value, dp)
                        lines.append(f"_bsdf.inputs['Emission Color'].default_value = {ec}")

            lines.append("")

        # --- Objects ---
        lines.append("# ============================================================")
        lines.append("# Objects")
        lines.append("# ============================================================")

        for obj in bpy.data.objects:
            if obj.type == 'CAMERA' and not self.include_camera:
                continue
            if obj.type == 'LIGHT' and not self.include_lights:
                continue

            loc = self._round_tuple(obj.location, dp)
            rot = self._round_tuple(obj.rotation_euler, dp)

            if obj.type == 'MESH':
                self._export_mesh(lines, obj, loc, rot, dp)
            elif obj.type == 'LIGHT':
                self._export_light(lines, obj, loc, rot, dp)
            elif obj.type == 'CAMERA':
                self._export_camera(lines, obj, loc, rot, dp)
            elif obj.type == 'EMPTY':
                scale = self._round_tuple(obj.scale, dp)
                self._export_empty(lines, obj, loc, rot, scale, dp)

            lines.append("")

        # --- Parent relationships ---
        parents = [(obj.name, obj.parent.name) for obj in bpy.data.objects if obj.parent]
        if parents:
            lines.append("# ============================================================")
            lines.append("# Parent Relationships")
            lines.append("# ============================================================")
            for child_name, parent_name in parents:
                lines.append(f"bpy.data.objects['{child_name}'].parent = bpy.data.objects['{parent_name}']")
            lines.append("")

        # Write file
        code = '\n'.join(lines) + '\n'
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(code)

        self.report({'INFO'}, f"Exported {len(bpy.data.objects)} objects to {filepath}")
        return {'FINISHED'}

    # ================================================================
    # Mesh export — with correct scale handling
    # ================================================================
    def _export_mesh(self, lines, obj, loc, rot, dp):
        mesh = obj.data
        vcount = len(mesh.vertices)
        fcount = len(mesh.polygons)

        # Compute the local mesh bounding box from actual vertex positions.
        # This captures applied transforms (Ctrl+A → Apply Scale) that bake
        # size into vertices while resetting obj.scale to (1,1,1).
        mesh_bbox = self._get_mesh_local_bbox(mesh)
        sx, sy, sz = obj.scale

        # For each primitive type:
        #   primitive_xxx_add(size=1) creates a base mesh of known dimensions.
        #   We compute export_scale = mesh_bbox * obj.scale so the result
        #   matches the original, whether or not scale was applied.

        if vcount == 8 and fcount == 6:
            # --- Cube (size=1 → base 1x1x1) ---
            export_scale = self._round_tuple(
                (mesh_bbox[0] * sx, mesh_bbox[1] * sy, mesh_bbox[2] * sz), dp)
            lines.append(f"bpy.ops.mesh.primitive_cube_add(size=1, location={loc})")
            self._write_obj_header(lines, obj, rot)
            lines.append(f"obj.scale = {export_scale}")

        elif vcount == 4 and fcount == 1:
            # --- Plane (size=1 → base 1x1) ---
            export_scale = self._round_tuple(
                (mesh_bbox[0] * sx, mesh_bbox[1] * sy, sz), dp)
            lines.append(f"bpy.ops.mesh.primitive_plane_add(size=1, location={loc})")
            self._write_obj_header(lines, obj, rot)
            lines.append(f"obj.scale = {export_scale}")

        elif fcount >= 30 and fcount <= 66:
            # --- Cylinder (32-side default) ---
            local_radius = max(mesh_bbox[0], mesh_bbox[1]) / 2
            local_depth = mesh_bbox[2]
            eff_radius = round(local_radius * max(sx, sy), dp)
            eff_depth = round(local_depth * sz, dp)
            lines.append(f"bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius={eff_radius}, depth={eff_depth}, location={loc})")
            self._write_obj_header(lines, obj, rot)
            # Handle non-uniform XY scaling (elliptical cross-section)
            if abs(sx - sy) > 0.001 and sy != 0:
                ratio = round(sx / sy, dp)
                lines.append(f"obj.scale = ({ratio}, 1.0, 1.0)")

        elif vcount >= 100 and self._is_sphere_like(mesh):
            # --- Sphere ---
            eff_radius = round(max(mesh_bbox) / 2 * max(obj.scale), dp)
            lines.append(f"bpy.ops.mesh.primitive_uv_sphere_add(radius={eff_radius}, location={loc})")
            self._write_obj_header(lines, obj, rot)

        else:
            # --- Complex mesh (approximated as cube) ---
            export_scale = self._round_tuple(
                (mesh_bbox[0] * sx, mesh_bbox[1] * sy, mesh_bbox[2] * sz), dp)
            lines.append(f"# NOTE: Complex mesh '{obj.name}' (verts={vcount}, faces={fcount})")
            lines.append(f"# Approximated as cube — replace with imported geometry for exact match")
            lines.append(f"bpy.ops.mesh.primitive_cube_add(size=1, location={loc})")
            self._write_obj_header(lines, obj, rot)
            lines.append(f"obj.scale = {export_scale}")

        # Mesh data name
        if obj.data.name != obj.name:
            lines.append(f"obj.data.name = '{obj.data.name}'")

        # Material
        if obj.material_slots and obj.material_slots[0].material:
            mat_name = obj.material_slots[0].material.name
            lines.append(f"obj.data.materials.append(bpy.data.materials['{mat_name}'])")

    def _write_obj_header(self, lines, obj, rot):
        """Common lines after creating any object."""
        lines.append(f"obj = bpy.context.active_object")
        lines.append(f"obj.name = '{obj.name}'")
        lines.append(f"obj.rotation_euler = {rot}")

    # ----------------------------------------------------------------
    # Light export
    # ----------------------------------------------------------------
    def _export_light(self, lines, obj, loc, rot, dp):
        light = obj.data
        lines.append(f"bpy.ops.object.light_add(type='{light.type}', location={loc})")
        self._write_obj_header(lines, obj, rot)
        lines.append(f"obj.data.energy = {round(light.energy, dp)}")
        if hasattr(light, 'color'):
            c = self._round_tuple(light.color, dp)
            if c != (1.0, 1.0, 1.0):
                lines.append(f"obj.data.color = {c}")
        if light.type == 'AREA':
            lines.append(f"obj.data.size = {round(light.size, dp)}")
            if hasattr(light, 'size_y') and light.shape in ('RECTANGLE', 'ELLIPSE'):
                lines.append(f"obj.data.shape = '{light.shape}'")
                lines.append(f"obj.data.size_y = {round(light.size_y, dp)}")
        elif light.type == 'POINT':
            lines.append(f"obj.data.shadow_soft_size = {round(light.shadow_soft_size, dp)}")
        elif light.type == 'SPOT':
            lines.append(f"obj.data.spot_size = {round(light.spot_size, dp)}")
            lines.append(f"obj.data.spot_blend = {round(light.spot_blend, dp)}")

    # ----------------------------------------------------------------
    # Camera export
    # ----------------------------------------------------------------
    def _export_camera(self, lines, obj, loc, rot, dp):
        cam = obj.data
        lines.append(f"bpy.ops.object.camera_add(location={loc})")
        self._write_obj_header(lines, obj, rot)
        lines.append(f"obj.data.lens = {round(cam.lens, dp)}")
        lines.append(f"obj.data.clip_start = {round(cam.clip_start, dp)}")
        lines.append(f"obj.data.clip_end = {round(cam.clip_end, dp)}")
        if cam.sensor_width != 36.0:
            lines.append(f"obj.data.sensor_width = {round(cam.sensor_width, dp)}")

    # ----------------------------------------------------------------
    # Empty export
    # ----------------------------------------------------------------
    def _export_empty(self, lines, obj, loc, rot, scale, dp):
        lines.append(f"bpy.ops.object.empty_add(type='{obj.empty_display_type}', location={loc})")
        self._write_obj_header(lines, obj, rot)
        lines.append(f"obj.scale = {scale}")
        lines.append(f"obj.empty_display_size = {round(obj.empty_display_size, dp)}")

    # ----------------------------------------------------------------
    # Helpers
    # ----------------------------------------------------------------
    def _mat_var(self, name):
        """Convert material name to a valid Python variable name."""
        return "mat_" + name.replace(".", "_").replace(" ", "_").replace("-", "_")

    def _round_tuple(self, values, dp):
        return tuple(round(v, dp) for v in values)

    def _get_mesh_local_bbox(self, mesh):
        """
        Get the local bounding box dimensions from actual mesh vertex positions.
        This correctly captures applied scale transforms (where obj.scale is 1
        but the mesh vertices define a larger shape).
        """
        if len(mesh.vertices) == 0:
            return (1.0, 1.0, 1.0)
        verts = [v.co for v in mesh.vertices]
        min_co = [min(v[i] for v in verts) for i in range(3)]
        max_co = [max(v[i] for v in verts) for i in range(3)]
        bbox = []
        for i in range(3):
            size = max_co[i] - min_co[i]
            # Use 1.0 for zero-thickness dimensions (e.g. plane Z-axis)
            # so that obj.scale on that axis passes through unchanged
            bbox.append(size if size > 0.00001 else 1.0)
        return tuple(bbox)

    def _is_sphere_like(self, mesh):
        """Rough heuristic: check if mesh is roughly spherical."""
        if len(mesh.vertices) < 50:
            return False
        import mathutils
        center = mathutils.Vector((0, 0, 0))
        for v in mesh.vertices:
            center += v.co
        center /= len(mesh.vertices)
        dists = [(v.co - center).length for v in mesh.vertices]
        avg = sum(dists) / len(dists)
        if avg < 0.001:
            return False
        variance = sum((d - avg) ** 2 for d in dists) / len(dists)
        return (variance / (avg * avg)) < 0.05


# ============================================================
# Registration
# ============================================================
def menu_func_export(self, context):
    self.layout.operator(ExportBpyCode.bl_idname, text="Blender Python Script (.py)")


def register():
    bpy.utils.register_class(ExportBpyCode)
    bpy.types.TOPBAR_MT_file_export.append(menu_func_export)


def unregister():
    bpy.utils.unregister_class(ExportBpyCode)
    bpy.types.TOPBAR_MT_file_export.remove(menu_func_export)


if __name__ == "__main__":
    register()