bl_info = {
    "name": "Export Scene as BPY Code",
    "author": "BVB Tools",
    "version": (1, 2, 1),
    "blender": (3, 6, 0),
    "location": "File > Export > Blender Python Script (.py)",
    "description": "Export the current scene as a reproducible bpy Python script",
    "category": "Import-Export",
}

import bpy
import math
from bpy_extras.io_utils import ExportHelper
from bpy.props import StringProperty, BoolProperty, EnumProperty


class ExportBpyCode(bpy.types.Operator, ExportHelper):
    """Export the current scene as a bpy Python script that can reconstruct it"""
    bl_idname = "export_scene.bpy_code"
    bl_label = "Export BPY Code"

    filename_ext = ".py"

    filter_glob: StringProperty(
        default="*.py",
        options={'HIDDEN'},
        maxlen=255,
    )

    include_clear_scene: BoolProperty(
        name="Include Clear Scene",
        description="Add code to clear the scene before rebuilding",
        default=True,
    )

    include_camera: BoolProperty(
        name="Include Camera",
        description="Export camera objects",
        default=True,
    )

    include_lights: BoolProperty(
        name="Include Lights",
        description="Export light objects",
        default=True,
    )

    include_render_settings: BoolProperty(
        name="Include Render Settings",
        description="Export render engine, resolution, and world environment settings",
        default=True,
    )

    skip_hidden: BoolProperty(
        name="Skip Hidden Objects",
        description="Don't export objects hidden in viewport (eye icon off)",
        default=False,
    )

    decimal_places: EnumProperty(
        name="Precision",
        description="Number of decimal places for coordinates",
        items=[
            ('4', "4 digits", ""),
            ('6', "6 digits (default)", ""),
            ('8', "8 digits", ""),
        ],
        default='6',
    )

    def execute(self, context):
        return self.export_scene(context, self.filepath)

    def export_scene(self, context, filepath):
        dp = int(self.decimal_places)
        lines = []
        self._complex_meshes = []  # Track non-primitive meshes

        lines.append('"""')
        lines.append(f"Blender Scene: {bpy.path.basename(bpy.data.filepath) or 'Untitled'}")
        lines.append(f"Objects: {len(bpy.data.objects)}")
        lines.append(f"Materials: {len(bpy.data.materials)}")
        lines.append(f"Generated by Export BPY Code addon v{'.'.join(str(x) for x in bl_info['version'])}")
        lines.append('"""')
        lines.append("")
        lines.append("import bpy")
        lines.append("import math")
        lines.append("")

        # --- Clear Scene ---
        if self.include_clear_scene:
            lines.append("# ============================================================")
            lines.append("# Clear Scene")
            lines.append("# ============================================================")
            lines.append("bpy.ops.object.select_all(action='SELECT')")
            lines.append("bpy.ops.object.delete(use_global=False)")
            lines.append("for m in list(bpy.data.materials): bpy.data.materials.remove(m)")
            lines.append("for m in list(bpy.data.meshes): bpy.data.meshes.remove(m)")
            lines.append("for m in list(bpy.data.lights): bpy.data.lights.remove(m)")
            lines.append("for m in list(bpy.data.cameras): bpy.data.cameras.remove(m)")
            lines.append("")

        # --- Render Settings ---
        if self.include_render_settings:
            scene = context.scene
            lines.append("# ============================================================")
            lines.append("# Render Settings")
            lines.append("# ============================================================")
            lines.append(f"bpy.context.scene.render.engine = '{scene.render.engine}'")
            lines.append(f"bpy.context.scene.render.resolution_x = {scene.render.resolution_x}")
            lines.append(f"bpy.context.scene.render.resolution_y = {scene.render.resolution_y}")
            lines.append(f"bpy.context.scene.render.resolution_percentage = {scene.render.resolution_percentage}")
            if scene.render.engine == 'CYCLES':
                lines.append(f"bpy.context.scene.cycles.samples = {scene.cycles.samples}")
            elif scene.render.engine == 'BLENDER_EEVEE':
                if hasattr(scene.eevee, 'taa_render_samples'):
                    lines.append(f"bpy.context.scene.eevee.taa_render_samples = {scene.eevee.taa_render_samples}")
            lines.append("")

            # World / environment
            world = scene.world
            if world and world.use_nodes:
                lines.append("# World Environment")
                lines.append("world = bpy.context.scene.world")
                lines.append("if world is None:")
                lines.append("    world = bpy.data.worlds.new('World')")
                lines.append("    bpy.context.scene.world = world")
                lines.append("world.use_nodes = True")
                lines.append("_bg = world.node_tree.nodes.get('Background')")
                lines.append("if _bg:")
                for node in world.node_tree.nodes:
                    if node.type == 'BACKGROUND':
                        bg_color = self._round_tuple(
                            node.inputs['Color'].default_value, dp)
                        bg_strength = round(
                            node.inputs['Strength'].default_value, dp)
                        lines.append(
                            f"    _bg.inputs['Color'].default_value = {bg_color}")
                        lines.append(
                            f"    _bg.inputs['Strength'].default_value = {bg_strength}")
                        break
                lines.append("")

        # --- Materials ---
        lines.append("# ============================================================")
        lines.append("# Materials")
        lines.append("# ============================================================")
        self._linked_materials = []  # Track materials with non-trivial node setups

        for mat in bpy.data.materials:
            if not mat.use_nodes or not mat.node_tree:
                continue
            bsdf = None
            for node in mat.node_tree.nodes:
                if node.type == 'BSDF_PRINCIPLED':
                    bsdf = node
                    break
            if not bsdf:
                continue

            # Warn about linked inputs (textures, color ramps, etc.)
            bc_input = bsdf.inputs['Base Color']
            if bc_input.is_linked:
                from_node = bc_input.links[0].from_node
                self._linked_materials.append(
                    f"{mat.name} (Base Color <- {from_node.type})")

            var = self._mat_var(mat.name)
            bc = self._round_tuple(bsdf.inputs['Base Color'].default_value, dp)
            rough = round(bsdf.inputs['Roughness'].default_value, dp)
            metal = round(bsdf.inputs['Metallic'].default_value, dp)

            lines.append(f"{var} = bpy.data.materials.new(name='{mat.name}')")
            lines.append(f"{var}.use_nodes = True")
            lines.append(f"_bsdf = {var}.node_tree.nodes['Principled BSDF']")
            lines.append(f"_bsdf.inputs['Base Color'].default_value = {bc}")
            lines.append(f"_bsdf.inputs['Roughness'].default_value = {rough}")
            lines.append(f"_bsdf.inputs['Metallic'].default_value = {metal}")

            # Alpha (only if non-opaque)
            if 'Alpha' in bsdf.inputs:
                alpha = round(bsdf.inputs['Alpha'].default_value, dp)
                if alpha < 0.999:
                    lines.append(f"_bsdf.inputs['Alpha'].default_value = {alpha}")
                    lines.append(f"{var}.blend_method = 'BLEND'")

            # Emission (only export if strength > 0)
            if 'Emission Strength' in bsdf.inputs:
                es = bsdf.inputs['Emission Strength'].default_value
                if es > 0.001:
                    lines.append(f"_bsdf.inputs['Emission Strength'].default_value = {round(es, dp)}")
                    if 'Emission Color' in bsdf.inputs:
                        ec = self._round_tuple(bsdf.inputs['Emission Color'].default_value, dp)
                        lines.append(f"_bsdf.inputs['Emission Color'].default_value = {ec}")

            lines.append("")

        # --- Objects ---
        lines.append("# ============================================================")
        lines.append("# Objects")
        lines.append("# ============================================================")

        self._complex_meshes = []  # Track complex meshes for warning

        for obj in bpy.data.objects:
            if obj.type == 'CAMERA' and not self.include_camera:
                continue
            if obj.type == 'LIGHT' and not self.include_lights:
                continue
            if self.skip_hidden and obj.hide_viewport:
                continue

            loc = self._round_tuple(obj.location, dp)
            rot = self._round_tuple(obj.rotation_euler, dp)

            if obj.type == 'MESH':
                self._export_mesh(lines, obj, loc, rot, dp)
            elif obj.type == 'LIGHT':
                self._export_light(lines, obj, loc, rot, dp)
            elif obj.type == 'CAMERA':
                self._export_camera(lines, obj, loc, rot, dp)
            elif obj.type == 'EMPTY':
                scale = self._round_tuple(obj.scale, dp)
                self._export_empty(lines, obj, loc, rot, scale, dp)

            # Preserve visibility state
            if obj.hide_viewport:
                lines.append(f"obj.hide_viewport = True")
            if obj.hide_render:
                lines.append(f"obj.hide_render = True")

            lines.append("")

        # --- Parent relationships ---
        parents = [(obj.name, obj.parent.name) for obj in bpy.data.objects if obj.parent]
        if parents:
            lines.append("# ============================================================")
            lines.append("# Parent Relationships")
            lines.append("# ============================================================")
            for child_name, parent_name in parents:
                lines.append(f"bpy.data.objects['{child_name}'].parent = bpy.data.objects['{parent_name}']")
            lines.append("")

        # Write file
        code = '\n'.join(lines) + '\n'
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(code)

        # Report results
        warnings = []
        if self._complex_meshes:
            names = ', '.join(self._complex_meshes[:8])
            suffix = f' (+{len(self._complex_meshes) - 8} more)' if len(self._complex_meshes) > 8 else ''
            warnings.append(
                f"{len(self._complex_meshes)} complex mesh(es) approximated as cubes: {names}{suffix}")
        if self._linked_materials:
            names = ', '.join(self._linked_materials[:5])
            warnings.append(
                f"{len(self._linked_materials)} material(s) use textures/nodes (only fallback color exported): {names}")

        if warnings:
            self.report({'WARNING'},
                f"Exported {len(bpy.data.objects)} objects. " + " | ".join(warnings))
        else:
            self.report({'INFO'}, f"Exported {len(bpy.data.objects)} objects to {filepath}")
        return {'FINISHED'}

    # ================================================================
    # Mesh export — with correct scale handling
    # ================================================================
    def _export_mesh(self, lines, obj, loc, rot, dp):
        mesh = obj.data
        vcount = len(mesh.vertices)
        fcount = len(mesh.polygons)

        # Compute the local mesh bounding box from actual vertex positions.
        # This captures applied transforms (Ctrl+A → Apply Scale) that bake
        # size into vertices while resetting obj.scale to (1,1,1).
        mesh_bbox = self._get_mesh_local_bbox(mesh)
        sx, sy, sz = obj.scale

        # For each primitive type:
        #   primitive_xxx_add(size=1) creates a base mesh of known dimensions.
        #   We compute export_scale = mesh_bbox * obj.scale so the result
        #   matches the original, whether or not scale was applied.

        if vcount == 8 and fcount == 6:
            # --- Cube (size=1 → base 1x1x1) ---
            export_scale = self._round_tuple(
                (mesh_bbox[0] * sx, mesh_bbox[1] * sy, mesh_bbox[2] * sz), dp)
            lines.append(f"bpy.ops.mesh.primitive_cube_add(size=1, location={loc})")
            self._write_obj_header(lines, obj, rot)
            lines.append(f"obj.scale = {export_scale}")

        elif vcount == 4 and fcount == 1:
            # --- Plane (size=1 → base 1x1) ---
            export_scale = self._round_tuple(
                (mesh_bbox[0] * sx, mesh_bbox[1] * sy, sz), dp)
            lines.append(f"bpy.ops.mesh.primitive_plane_add(size=1, location={loc})")
            self._write_obj_header(lines, obj, rot)
            lines.append(f"obj.scale = {export_scale}")

        elif vcount >= 100 and self._is_torus_like(mesh, vcount, fcount):
            # --- Torus (before cylinder — similar tri-count meshes) ---
            major_r = round((mesh_bbox[0] + mesh_bbox[1]) / 4 * max(sx, sy), dp)
            minor_r = round(mesh_bbox[2] / 2 * sz, dp)
            lines.append(f"bpy.ops.mesh.primitive_torus_add(major_radius={major_r}, minor_radius={minor_r}, location={loc})")
            self._write_obj_header(lines, obj, rot)

        elif vcount >= 50 and self._is_sphere_like(mesh):
            # --- Sphere ---
            eff_radius = round(max(mesh_bbox) / 2 * max(obj.scale), dp)
            lines.append(f"bpy.ops.mesh.primitive_uv_sphere_add(radius={eff_radius}, location={loc})")
            self._write_obj_header(lines, obj, rot)

        elif (cyl := self._analyze_cylinder(mesh, vcount, fcount)):
            # --- Cylinder / cone (triangulated caps, high segment count, any local axis) ---
            ax = cyl['axis']
            rot_c = self._rotation_for_aligned_cylinder(obj, ax, dp)
            local_depth, local_radius, s_depth, s_r1, s_r2 = (
                self._cylinder_bbox_scales(mesh_bbox, ax, sx, sy, sz))
            eff_radius = round(local_radius * max(s_r1, s_r2), dp)
            eff_depth = round(local_depth * s_depth, dp)
            if cyl['is_cone']:
                lines.append(
                    f"bpy.ops.mesh.primitive_cone_add(vertices=32, radius1={eff_radius}, depth={eff_depth}, location={loc})")
                self._write_obj_header(lines, obj, rot_c)
            else:
                lines.append(
                    f"bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius={eff_radius}, depth={eff_depth}, location={loc})")
                self._write_obj_header(lines, obj, rot_c)
                # Elliptical cross-section only when height is Z (no extra align);
                # after X/Y align, non-uniform scale maps messily to local axes.
                if ax == 2 and abs(sx - sy) > 0.001 and sy != 0:
                    ratio = round(sx / sy, dp)
                    lines.append(f"obj.scale = ({ratio}, 1.0, 1.0)")

        else:
            # --- Complex mesh (approximated as cube) ---
            self._complex_meshes.append(f"{obj.name} ({vcount}v/{fcount}f)")
            export_scale = self._round_tuple(
                (mesh_bbox[0] * sx, mesh_bbox[1] * sy, mesh_bbox[2] * sz), dp)
            lines.append(f"# WARNING: Complex mesh '{obj.name}' (verts={vcount}, faces={fcount})")
            lines.append(f"# Approximated as cube — replace with primitives for exact reconstruction")
            lines.append(f"bpy.ops.mesh.primitive_cube_add(size=1, location={loc})")
            self._write_obj_header(lines, obj, rot)
            lines.append(f"obj.scale = {export_scale}")

        # Mesh data name
        if obj.data.name != obj.name:
            lines.append(f"obj.data.name = '{obj.data.name}'")

        # Material
        if obj.material_slots and obj.material_slots[0].material:
            mat_name = obj.material_slots[0].material.name
            lines.append(f"obj.data.materials.append(bpy.data.materials['{mat_name}'])")

    def _write_obj_header(self, lines, obj, rot):
        """Common lines after creating any object."""
        lines.append(f"obj = bpy.context.active_object")
        lines.append(f"obj.name = '{obj.name}'")
        lines.append(f"obj.rotation_euler = {rot}")

    # ----------------------------------------------------------------
    # Light export
    # ----------------------------------------------------------------
    def _export_light(self, lines, obj, loc, rot, dp):
        light = obj.data
        lines.append(f"bpy.ops.object.light_add(type='{light.type}', location={loc})")
        self._write_obj_header(lines, obj, rot)
        lines.append(f"obj.data.energy = {round(light.energy, dp)}")
        if hasattr(light, 'color'):
            c = self._round_tuple(light.color, dp)
            if c != (1.0, 1.0, 1.0):
                lines.append(f"obj.data.color = {c}")
        if light.type == 'AREA':
            lines.append(f"obj.data.size = {round(light.size, dp)}")
            if hasattr(light, 'size_y') and light.shape in ('RECTANGLE', 'ELLIPSE'):
                lines.append(f"obj.data.shape = '{light.shape}'")
                lines.append(f"obj.data.size_y = {round(light.size_y, dp)}")
        elif light.type == 'POINT':
            lines.append(f"obj.data.shadow_soft_size = {round(light.shadow_soft_size, dp)}")
        elif light.type == 'SPOT':
            lines.append(f"obj.data.spot_size = {round(light.spot_size, dp)}")
            lines.append(f"obj.data.spot_blend = {round(light.spot_blend, dp)}")

    # ----------------------------------------------------------------
    # Camera export
    # ----------------------------------------------------------------
    def _export_camera(self, lines, obj, loc, rot, dp):
        cam = obj.data
        lines.append(f"bpy.ops.object.camera_add(location={loc})")
        self._write_obj_header(lines, obj, rot)
        lines.append(f"obj.data.lens = {round(cam.lens, dp)}")
        lines.append(f"obj.data.clip_start = {round(cam.clip_start, dp)}")
        lines.append(f"obj.data.clip_end = {round(cam.clip_end, dp)}")
        if cam.sensor_width != 36.0:
            lines.append(f"obj.data.sensor_width = {round(cam.sensor_width, dp)}")

    # ----------------------------------------------------------------
    # Empty export
    # ----------------------------------------------------------------
    def _export_empty(self, lines, obj, loc, rot, scale, dp):
        lines.append(f"bpy.ops.object.empty_add(type='{obj.empty_display_type}', location={loc})")
        self._write_obj_header(lines, obj, rot)
        lines.append(f"obj.scale = {scale}")
        lines.append(f"obj.empty_display_size = {round(obj.empty_display_size, dp)}")

    # ----------------------------------------------------------------
    # Helpers
    # ----------------------------------------------------------------
    def _mat_var(self, name):
        """Convert material name to a valid Python variable name."""
        return "mat_" + name.replace(".", "_").replace(" ", "_").replace("-", "_")

    def _round_tuple(self, values, dp):
        return tuple(round(v, dp) for v in values)

    def _get_mesh_local_bbox(self, mesh):
        """
        Get the local bounding box dimensions from actual mesh vertex positions.
        This correctly captures applied scale transforms (where obj.scale is 1
        but the mesh vertices define a larger shape).
        """
        if len(mesh.vertices) == 0:
            return (1.0, 1.0, 1.0)
        verts = [v.co for v in mesh.vertices]
        min_co = [min(v[i] for v in verts) for i in range(3)]
        max_co = [max(v[i] for v in verts) for i in range(3)]
        bbox = []
        for i in range(3):
            size = max_co[i] - min_co[i]
            # Use 1.0 for zero-thickness dimensions (e.g. plane Z-axis)
            # so that obj.scale on that axis passes through unchanged
            bbox.append(size if size > 0.00001 else 1.0)
        return tuple(bbox)

    def _is_sphere_like(self, mesh):
        """Rough heuristic: check if mesh is roughly spherical."""
        if len(mesh.vertices) < 50:
            return False
        import mathutils
        center = mathutils.Vector((0, 0, 0))
        for v in mesh.vertices:
            center += v.co
        center /= len(mesh.vertices)
        dists = [(v.co - center).length for v in mesh.vertices]
        avg = sum(dists) / len(dists)
        if avg < 0.001:
            return False
        variance = sum((d - avg) ** 2 for d in dists) / len(dists)
        return (variance / (avg * avg)) < 0.05

    def _is_torus_like(self, mesh, vcount, fcount):
        """Heuristic: torus has equal vert/face count and a hole in the center."""
        if abs(vcount - fcount) > 2:
            return False
        # Check for hole: center of mesh should have no vertices nearby
        import mathutils
        center = mathutils.Vector((0, 0, 0))
        for v in mesh.vertices:
            center += v.co
        center /= vcount
        min_dist = min((v.co - center).length for v in mesh.vertices)
        max_dist = max((v.co - center).length for v in mesh.vertices)
        # Torus has a hole, so min_dist should be significantly > 0
        if max_dist < 0.001:
            return False
        return (min_dist / max_dist) > 0.2

    def _axis_span(self, mesh, axis):
        vals = [v.co[axis] for v in mesh.vertices]
        return max(vals) - min(vals)

    def _is_circular_2d(self, verts_2d):
        """Low radial variance around centroid → circular cap in projection."""
        if len(verts_2d) < 6:
            return False
        cx = sum(v[0] for v in verts_2d) / len(verts_2d)
        cy = sum(v[1] for v in verts_2d) / len(verts_2d)
        dists = [math.hypot(v[0] - cx, v[1] - cy) for v in verts_2d]
        avg_d = sum(dists) / len(dists)
        if avg_d < 1e-5:
            return False
        variance = sum((d - avg_d) ** 2 for d in dists) / len(dists)
        return (variance / (avg_d * avg_d)) < 0.08

    def _cylinder_geometry_along_axis(self, mesh, axis):
        """True if verts split along `axis` into two stacks with circular cross-section."""
        verts = mesh.vertices
        if len(verts) < 8:
            return False

        def coord(vco):
            return vco[axis]

        def proj(vco):
            if axis == 0:
                return (vco[1], vco[2])
            if axis == 1:
                return (vco[0], vco[2])
            return (vco[0], vco[1])

        vals = [coord(v.co) for v in verts]
        vmin, vmax = min(vals), max(vals)
        if vmax - vmin < 1e-5:
            return False
        vmid = (vmin + vmax) / 2
        top = [v.co for v in verts if coord(v.co) > vmid]
        bot = [v.co for v in verts if coord(v.co) <= vmid]
        if not top or not bot:
            return False
        if max(len(top), len(bot)) > 2 * min(len(top), len(bot)) + 6:
            return False

        top_xy = [proj(v) for v in top]
        bot_xy = [proj(v) for v in bot]
        ok_top = self._is_circular_2d(top_xy)
        ok_bot = self._is_circular_2d(bot_xy)
        if ok_top and ok_bot:
            return True
        # Cone: one bucket is the apex (few verts), the other is the base cap
        if ok_top and len(bot_xy) <= 8:
            return True
        if ok_bot and len(top_xy) <= 8:
            return True
        return False

    def _analyze_cylinder(self, mesh, vcount, fcount):
        """
        Detect cylinder/cone including triangulated caps, high segment counts,
        and mesh-local axis not aligned to Z (edit-mode rotation).
        """
        if vcount < 8 or fcount < 10 or fcount > 520:
            return None
        if vcount >= 100 and self._is_torus_like(mesh, vcount, fcount):
            return None
        if vcount >= 50 and self._is_sphere_like(mesh):
            return None

        ngon_expected_v = 2 * (fcount - 2)
        loosely_prism = (
            abs(vcount - ngon_expected_v) <= max(8, vcount // 6)
            or (
                vcount >= 16
                and fcount >= vcount // 2
                and fcount <= vcount * 6 + 8
            )
        )
        if not loosely_prism and (vcount > 320 or fcount > 520):
            return None

        candidates = []
        for a in (2, 0, 1):
            if self._cylinder_geometry_along_axis(mesh, a):
                candidates.append((self._axis_span(mesh, a), a))
        if not candidates:
            return None
        axis = max(candidates, key=lambda t: t[0])[1]
        return {'axis': axis, 'is_cone': self._is_cone_like(mesh)}

    def _rotation_for_aligned_cylinder(self, obj, axis, dp):
        """`primitive_*_cylinder/cone` is Z-high; rotate object if mesh height is on X/Y."""
        import mathutils

        if axis == 2:
            return self._round_tuple(obj.rotation_euler, dp)
        if axis == 0:
            e_align = mathutils.Euler((0.0, math.pi / 2, 0.0), 'XYZ')
        else:
            e_align = mathutils.Euler((-math.pi / 2, 0.0, 0.0), 'XYZ')
        e_orig = mathutils.Euler(obj.rotation_euler, 'XYZ')
        m = e_orig.to_matrix() @ e_align.to_matrix()
        e = m.to_euler('XYZ')
        return self._round_tuple((e.x, e.y, e.z), dp)

    def _cylinder_bbox_scales(self, mesh_bbox, axis, sx, sy, sz):
        """
        Bounding-box height along cylinder axis and radius from the other two axes;
        returns (depth, radius, scale_depth, scale_r1, scale_r2).
        """
        bx, by, bz = mesh_bbox
        if axis == 0:
            return bx, max(by, bz) / 2, sx, sy, sz
        if axis == 1:
            return by, max(bx, bz) / 2, sy, sx, sz
        return bz, max(bx, by) / 2, sz, sx, sy

    def _is_cone_like(self, mesh):
        """Heuristic: cone has one apex vertex where many edges converge."""
        if len(mesh.vertices) < 10:
            return False
        # Find the vertex connected to the most edges
        edge_count = {}
        for e in mesh.edges:
            for vi in e.vertices:
                edge_count[vi] = edge_count.get(vi, 0) + 1
        max_edges = max(edge_count.values()) if edge_count else 0
        # Cone apex connects to all base vertices (32 for 32-side cone)
        return max_edges >= 16


# ============================================================
# Registration
# ============================================================
def menu_func_export(self, context):
    self.layout.operator(ExportBpyCode.bl_idname, text="Blender Python Script (.py)")


def register():
    # Prevent duplicate registration when running via Script Editor
    try:
        bpy.utils.unregister_class(ExportBpyCode)
    except RuntimeError:
        pass
    try:
        bpy.types.TOPBAR_MT_file_export.remove(menu_func_export)
    except ValueError:
        pass

    bpy.utils.register_class(ExportBpyCode)
    bpy.types.TOPBAR_MT_file_export.append(menu_func_export)


def unregister():
    try:
        bpy.utils.unregister_class(ExportBpyCode)
    except RuntimeError:
        pass
    try:
        bpy.types.TOPBAR_MT_file_export.remove(menu_func_export)
    except ValueError:
        pass


if __name__ == "__main__":
    register()